name: Debug Build

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - 'fastlane/**'
    - 'scripts/**'
    - 'README.md'
    - 'yarn.lock'
    - 'package.json'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'fastlane/**'
      - 'scripts/**'
      - 'README.md'
      - 'yarn.lock'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: AppManager-DEBUG#${{ github.run_number }}
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Restore toybox
      uses: actions/cache@v2
      with:
        path: |
          toybox/src/main/jniLibs
        key: ${{ runner.os }}-${{ hashFiles('toybox/toybox/**') }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Rename the APK file
      run: mv ./app/build/outputs/apk/debug/app-universal-debug.apk ./${{ APP_NAME }}.apk
    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: ${{ APP_NAME }}
        path: ./${{ APP_NAME }}.apk
    - name: Upload APK to telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: ./${{ APP_NAME }}.apk
        format: html
        message: |
          <strong>AM Debug Run#${{ github.run_number }}</strong>

          <em>${{ github.event.head_commit.message }}</em>
